alshaya_search_algolia.settings:
  type: config_object
  label: 'Alshaya search algolia configuration'
  mapping:
    show_terms_in_lhn:
      type: string
      label: 'Show terms in lhn'
      description: 'Values could be either all or L1'
    index_from_drupal:
      type: boolean
      label: 'Algolia Index from Drupal'
      description: 'Determines if Algolia indexation happens from Drupal or Magento'
    index_prefix:
      type: string
      label: 'Algolia Index Prefix'
      description: 'Store index prefix for Drupal or MDC indexes'
    index_sku_as_object_id:
      type: boolean
      label: 'Flag to determine if we use SKU as objectID for search indexes'
