permissions:
  - 'restful get delivery_methods'
  - 'restful get alshaya_static_texts'
  - 'restful get social_media_links'
  - 'restful get categories'
  - 'restful get simple_page'
  - 'restful get advanced_page'
  - 'restful get category_product_list'
  - 'restful get stores_finder'
  - 'restful get stores_finder_collection'
  - 'restful get promotion_product_list'
  - 'restful get search_page_product_list'
  - 'restful get knet_init_request'
  - 'restful get knet_finalize_request'
  - 'restful get deeplink'
  - 'restful get payment_methods'
  - 'restful get cart_promotions'
  - 'restful get stock'
  - 'restful get product_exclude_linked'
  - 'restful get magazine_detail_page'
