alshaya_algolia_react.settings:
  type: config_object
  label: 'Alshaya Algolia React settings'
  mapping:
    attributes_to_sort_by_name:
      type: sequence
      label: 'Attributes to sort by name'
      sequence:
        type: string
        label: 'Attribute'
    local_storage_expire:
      type: string
      label: 'Expire time for localStorage.'
    application_id:
      type: string
      label: 'Application id.'
    search_api_key:
      type: string
      label: 'Search api key.'
    hits:
      type: integer
      label: 'Number of results to show.'
    top_results:
      type: integer
      label: 'Number of top results to show for autocomplete.'
    items_per_page:
      type: integer
      label: 'Number of items to show for search results.'
    hide_grid_toggle:
      type: boolean
      label: 'Grid toggle hide/show in srp/plp.'
    add_to_bag_hover:
      type: boolean
      label: 'Enable add to bag hover effect on PLP product.'
    top_facets_limit:
      type: integer
      label: 'Number of filters to show on srp/plp page top.'
    default_col_grid:
      type: string
      label: 'Default col grid value.'
    default_col_grid_mobile:
      type: string
      label: 'Default col grid for mobile view.'
    show_article_swatches:
      type: boolean
      label: 'Enable article swatches on PLP and SRP product teasers.'
    enable_hits_per_page:
      type: boolean
      label: 'Enable/Disable hitsPerPage key from configuration.'
    render_single_result_facets:
      type: boolean
      label: 'Enable/Disable single result facets from configuration.'
    exclude_render_single_result_facets:
      type: string
      label: 'Exclude the filters from single results facets.'
    product_teaser_attributes:
      type: string
      label: 'Attributes to be displayed on PLP teaser.'
    algolia_facets_local_storage_expiry:
      type: integer
      label: 'Expiry in seconds for getting facets from algolia.'
    algolia_enable_configurable_filter:
      type: boolean
      label: 'Enable or disable configurable filters.'

alshaya_algolia_react.product_frames:
  type: config_object
  label: 'Alshaya algolia react product frames configurations'
  mapping:
    product_frame:
      type: boolean
      label: 'Display frame around the teaser on all listing pages'
    promotion_frame:
      type: boolean
      label: 'Display frame on promotion label on all listing pages'
    product_title_trim:
      type: boolean
      label: 'Display trimmed product title on all listing pages'

alshaya_algolia_react.color_swatches:
  type: config_object
  label: 'Alshaya color swatches configurations'
  mapping:
    enable_listing_page_color_swatch_slider:
      type: boolean
      label: 'Enable / Disable this color swatch with slider on listing pages.'
    swatch_type:
      type: string
      label: 'Display the swatch type circle, square'
    no_of_swatches_desktop:
      type: integer
      label: 'Set the swatch limit for PLP/SRP on desktop view'
    no_of_swatches_mobile:
      type: integer
      label: 'Set the swatch limit for PLP/SRP on mobile view'

alshaya_algolia_react.swipe_image:
  type: config_object
  label: 'Alshaya swipe image configurations'
  mapping:
    enable_swipe_image_mobile:
      type: boolean
      label: 'Enable / Disable swipe image on mobile view.'
    no_of_image_scroll:
      type: integer
      label: 'Set the swipe image scroll limit for PLP/SRP on desktop view'
    slide_effect:
      type: string
      label: 'Set the effect of slide'
    image_slide_timing:
      type: float
      label: 'Auto scroll timer for auto scrolling the product images on listing pages.'

alshaya_algolia_react.predictive_search:
  type: config_object
  label: 'Algolia Predictive Search Configuration'
  mapping:
    enable_predictive_search:
      type: boolean
      label: 'Enable Predictive Search'
    predictive_search_layout:
      type: string
      label: 'Desktop Layout for Predictive Search'
    recent_search_count:
      type: integer
      label: 'Number of recent searches to be displayed'
