# Schema for the configuration files of the alshaya main menu settings.

alshaya_main_menu.settings:
  type: config_object
  label: 'Main menu settings'
  mapping:
    mobile_main_menu_max_depth:
      type: integer
      label: 'Main menu maximum depth for mobile'
    desktop_main_menu_highlight_timing:
      type: integer
      label: 'Main menu transition timing for desktop'
    desktop_main_menu_layout:
      type: integer
      label: 'Main menu display on desktop'
    max_nb_col:
      type: integer
      label: 'Maxinum number of columns to show'
    ideal_max_col_length:
      type: integer
      label: 'Ideal length of the column'
