fields:
  color:
    configurable: 1
    cardinality: 1
    index: 0
    facet: 0
  size:
    configurable: 1
    cardinality: 1
    index: 0
    facet: 0
  color_lhn:
    label: 'Color'
    type: 'string'
    cardinality: -1
    index: 1
    facet: 1
    swatch: 1
  finish_lhn:
    label: 'Finish'
    cardinality: -1
    index: 1
    facet: 1
  furniturefinish_lhn:
    label: 'Furniture Finish'
    cardinality: -1
    index: 1
    facet: 1
  material_lhn:
    label: 'Material'
    cardinality: -1
    index: 1
    facet: 1
  material:
    label: 'Material'
    configurable: 1
  product_type_lhn:
    label: 'Product Type'
    cardinality: -1
    index: 1
    facet: 1
  product_type:
    label: 'Product Type'
    configurable: 1
  size_lhn:
    label: 'Size'
    cardinality: -1
    index: 1
    facet: 1
  style_lhn:
    label: 'Style'
    cardinality: -1
    index: 1
    facet: 1
  style:
    label: 'Style'
    configurable: 1
  finish:
    label: 'Finish'
    configurable: 1
  furniture_finish:
    label: 'Furniture Finish'
    configurable: 1
  height:
    label: 'Height'
    configurable: 1
  length:
    label: 'Length'
    configurable: 1
  frame:
    label: 'Frame'
    configurable: 1
  fabric:
    label: 'Fabric'
    configurable: 1
  white_glove_delivery:
    label: 'White Glove Delivery'
    type: 'string'
  group_name:
    label: 'Group Name'
    type: 'string'
  sku_name:
    label: 'SKU Name'
    type: 'string'
  short_description:
    label: 'Product Info'
    type: 'text_long'
  feature_lhn:
    label: 'Features'
    cardinality: -1
    index: 1
    facet: 1
