color_swatches: true
color_swatches_show_product_image: true
show_child_images_after_selecting: 'all'
show_parent_images_in_child: true
swatches:
  pdp:
    - color
    - finish
    - fabric
  plp:
    - color_lhn
hide_not_required_option: true
plp_slider:
  item: 3
  margin: 3
