# Update the hostname to the local development environment hostname.
vagrant_ip: 192.168.25.74
vagrant_hostname: local.alshaya.com
vagrant_machine_name: alshaya

# Use Ubuntu 16.04 LTS to match Acquia Cloud environments.
vagrant_box: geerlingguy/ubuntu1604

# Set drupal_site_name to the project's human-readable name.
drupal_site_name: "Alshaya"

# Provide the path to the project root to Vagrant.
vagrant_synced_folders:
  # Set the local_path for the first synced folder to `.`.
  - local_path: .
    # Set the destination to the Acquia Cloud subscription machine name.
    destination: /var/www/alshaya
    type: nfs

drupal_build_composer_project: false
# Toggling this to `true` would invoke `composer install` with the
# projects own `composer.json` successfully.
drupal_build_composer: false
drupal_composer_path: false
drupal_composer_install_dir: "/var/www/alshaya"
drupal_core_path: "/var/www/alshaya/docroot"
ssh_home: /var/www/alshaya

drupal_db_user: drupal
drupal_db_password: drupal
drupal_db_name: drupal

# Set this to 'false' if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
drupal_build_makefile: false
drupal_install_site: false

# Drupal VM automatically creates a drush alias file in your ~/.drush folder if
# this variable is 'true'.
configure_drush_aliases: false

# This is required for front-end building tools.
nodejs_version: "8.x"
nodejs_npm_global_packages:
  - name: bower
  - name: gulp-cli
  - name: yarn
nodejs_install_npm_user: "{{ drupalvm_user }}"
npm_config_prefix: "/home/{{ drupalvm_user }}/.npm-global"
installed_extras:
  - adminer
  - drush
  - mailhog
  - nodejs
  - selenium
  - solr
  - xdebug
  - memcached
  - tideways
  - varnish
  - pimpmylog
  - drupalconsole

php_version: '7.2'
php_packages_extra:
  - "php{{ php_version }}-bz2"
  - "php{{ php_version }}-bcmath"
  - "php{{ php_version }}-zip"
  - "php{{ php_version }}-imagick"
  - "php{{ php_version }}-xml"
  - "php{{ php_version }}-soap"
  - imagemagick

# Solr Configuration.
solr_version: "4.5.1"

# XDebug configuration.
# Change this value to 1 in order to enable xdebug by default.
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 0
# Change this value to "no" to enable xdebug on the cli.
php_xdebug_cli_disable: yes
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
php_xdebug_remote_port: "9000"
php_memory_limit: "256M"

post_provision_tasks_dir: "../../../acquia/blt/scripts/drupal-vm/post-provision.yml"
post_provision_scripts:
  - "../../../acquia/blt/scripts/drupal-vm/post-provision.php"
  - "../../../../box/scripts/configure-solr.sh"
  - "../../../../box/scripts/configure-varnish.sh"
  - "../../../../box/scripts/configure-oauth.sh"
  - "../../../../box/scripts/configure-ssl.sh"

apache_vhosts_ssl:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/home/vagrant/ssl/localhost.crt"
    certificate_key_file: "/home/vagrant/ssl/localhost.key"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"

apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-mckw.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-hmkw.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-mcsa.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-hmsa.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-mcae.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-hmae.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-hmeg.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-bbwkw.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-bbwsa.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-bbwae.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-vskw.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-vsae.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-vssa.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-bbme.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-dhuae.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-pbkw.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-pbsa.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-pbae.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-pbnontransacae.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-flkw.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-flsa.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-flae.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-kzkw.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-venontransacme.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-wekw.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-wesa.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-weae.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-jusnontransacae.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-jusnontransackw.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.alshaya-jusnontransacsa.com"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

mysql_databases:
  - name: drupal
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_mckw
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_hmkw
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_hmsa
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_mcae
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_hmae
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_hmeg
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_mcsa
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_bbwkw
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_bbwsa
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_bbwae
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_vskw
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_vsae
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_vssa
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_bbme
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_dhuae
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_pbkw
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_pbsa
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_pbae
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_pbnontransacae
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_flkw
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_flsa
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_flae
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_kzkw
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_venontransacme
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_wekw
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_wesa
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_weae
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_jusnontransacae
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_jusnontransackw
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: drupal_alshaya_jusnontransacsa
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: drupal
    host: "%"
    password: drupal
    priv: "*.*:ALL"

varnish_version: "4.1"
varnish_listen_port: "81"
varnish_default_backend_port: "80"

# Pimp my Log settings.
pimpmylog_install_dir: /usr/share/php/pimpmylog
pimpmylog_grant_all_privs: true

# MySQL settings.
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 1
mysql_wait_timeout: 300
