block.settings.alshaya_shop_by_block:
  type: block_settings
  label: 'Branding block'
  mapping:
    vocabulary:
      type: text
      label: 'Vocabulary'
    level:
      type: integer
      label: 'Starting level'

alshaya_acm_product_category.settings:
  type: config_object
  label: 'Alshaya ACM Product Category Settings'
  mapping:
    sale_category_ids:
      type: sequence
      label: 'Sale Category IDs'
      sequence:
        type: integer
        label: 'Taxonomy term ids'
    grouping_page_header_style:
      type: string
      label: 'Grouping Page Header Style'
