block.settings.alshaya_shop_by_block:
  type: block_settings
  label: 'Branding block'
  mapping:
    vocabulary:
      type: text
      label: 'Vocabulary'
    level:
      type: integer
      label: 'Starting level'

alshaya_acm_product_category.super_category.settings:
  type: config_object
  label: 'Category Menu settings'
  mapping:
    status:
      type: boolean
      label: 'Enable super category feature'
    default_category_tid:
      type: integer
      label: 'Default parent term id for main menu'
    footer_menu_blocks:
      type: sequence
      label: 'Menu types that needs to alter for footer'
      sequence:
        type: string
        label: 'Menu type'
