fields:
  product_brand:
    source: 'brand'
    index: 1
  color:
    facet: 0
    configurable: 1
    index: 1
  padding:
    label: 'Padding'
    index: 1
  bra_coverage:
    label: 'Bra Coverage'
    description: 'Bra Coverage.'
    index: 1
  labels:
    index: 1
  band_size:
    index: 1
  cup_size:
    index: 1
  fragrance:
    index: 1
  at_glance:
    index: 1
  style:
    index: 1
  season:
    index: 1
  collection:
    index: 1
  whats_in_the_box:
    index: 1
  bra_type:
    label: 'Bra Type'
    description: 'Bra Type.'
    index: 1
  # Psuedo field for grouping the band size and cup size.  
  bra_size:
    label: 'Bra Size'
    description: 'Bra Size.'
    facet: 1
    index: 1
    widget:
      type: multi_level_widget
