services:
  alshaya_config.config_subscriber:
    class: Drupal\alshaya_config\EventSubscriber\AlshayaConfigSubscriber
    arguments:
      - '@module_handler'
      - '@config.storage'
      - '@config.factory'
    tags:
      - {name: event_subscriber}
  alshaya_config.manager:
    class: Drupal\alshaya_config\AlshayaConfigManager
    arguments:
      - '@config.factory'
      - '@entity_type.manager'
      - '@theme.manager'
      - '@module_handler'
