services:
  alshaya_config.config_subscriber:
    class: Drupal\alshaya_config\EventSubscriber\AlshayaConfigSubscriber
    arguments:
      - '@module_handler'
      - '@config.storage'
      - '@config.factory'
      - '@alshaya.alshaya_array_utils'
      - '@current_user'
      - '@logger.factory'
    tags:
      - {name: event_subscriber}
  alshaya_config.manager:
    class: Drupal\alshaya_config\AlshayaConfigManager
    arguments:
      - '@config.factory'
      - '@language_manager'
      - '@entity_type.manager'
      - '@theme.manager'
      - '@module_handler'
      - '@logger.factory'
      - '@file_system'

  alshaya.alshaya_array_utils:
    class: Drupal\alshaya_config\AlshayaArrayUtils
