fields:
  target_area:
    label: 'Target Area'
    cardinality: -1
    facet: 1
    index: 1
  concern:
    label: 'Concern'
    cardinality: -1
    facet: 1
    index: 1
  range:
    label: 'Range'
    cardinality: -1
    facet: 1
    index: 1
  product_type_hb:
    label: 'Product Type'
    cardinality: -1
    facet: 1
    index: 1
  category_type:
    label: 'Category Type'
    cardinality: -1
    facet: 1
    index: 1
  vegan:
    label: 'Vegan'
    cardinality: -1
    facet: 1
    index: 1
  free_form:
    label: 'Free Form'
    cardinality: -1
    facet: 1
    index: 1
  finish:
    label: 'Finish'
    cardinality: -1
    facet: 1
    index: 1
  scent:
    label: 'Scent'
    cardinality: -1
    facet: 1
    index: 1
  coverage:
    label: 'Coverage'
    cardinality: -1
    facet: 1
    index: 1
  top_three_attributes_1:
    label: 'Top three attributes 1'
    type: 'text_long'
    description: 'Top three attributes 1'
  top_three_attributes_2:
    label: 'Top three attributes 2'
    type: 'text_long'
    description: 'Top three attributes 2'
  top_three_attributes_3:
    label: 'Top three attributes 3'
    type: 'text_long'
    description: 'Top three attributes 3'
  color:
    configurable: 1
    index: 0
    facet: 0
    display_configurable_for: 'color_swatch_code'
  color_swatch_code:
    label: 'Color swatch code'
    type: 'string'
    translatable: 0
  mainkeyingredients_name:
    label: 'Main key ingredients name'
    type: 'string'
    description: 'Main key ingredients name'
  mainkeyingredients_description:
    label: 'Main key ingredients description'
    type: 'text_long'
    description: 'Main key ingredients description'
  keyingredients_name2:
    label: 'Second Key Ingredient Name'
    type: 'string'
    description: 'Second Key Ingredient Name'
  keyingredients_description2:
    label: 'Second Key Ingredient description'
    type: 'text_long'
    description: 'Second Key Ingredient description'
  keyingredients_name3:
    label: 'Third Key Ingredient Name'
    type: 'string'
    description: 'Third Key Ingredient Name'
  keyingredients_description3:
    label: 'Third Key Ingredient description'
    type: 'text_long'
    description: 'Third Key Ingredient description'
  technical_ingredients_description:
    label: 'Technical Ingredients'
    type: 'text_long'
    description: 'Technical Ingredients'
