alshaya_online_returns.settings:
  type: config_object
  label: 'Online Returns Settings'
  mapping:
    status:
      type: boolean
      label: 'Config to enable/disable Online Returns feature'
    cart_banner:
      type: boolean
      label: 'Config to enable/disable Online Returns cart bannere'

alshaya_online_returns.return_confirmation:
  type: config_object
  label: 'Return confirmation settings'
  mapping:
    return_date_format:
      type: label
      label: 'Return Date format'
    rows:
      type: sequence
      label: 'Whats next row'
      sequence:
        - type: return_whats_next_row
    customer_service_number:
      type: string
      label: 'Config to show the customer service number'

return_whats_next_row:
  type: mapping
  label: 'Whats next row'
  mapping:
    title:
      type: label
      label: 'Title'
    description:
      type: text_format
      label: 'Description'
    icon:
      type: string
      label: 'Icon'
    hide_this_row:
      type: boolean
      label: 'Hide This Row'

alshaya_online_returns.egift_card_refund:
  type: config_object
  label: 'Return confirmation settings'
  mapping:
    egift_card_refund_enabled:
      type: boolean
      label: 'Config to enable/disable egift card during refund'
    not_supported_refund_payment_methods:
      label: 'Not supported payment methods for eGift card refund.'
      type: sequence
      sequence:
        type: string
    egift_refund_text:
      type: string
      label: 'Config to show the message under the eGift card refund option'
    egift_card_icon:
      type: file
      label: 'Config to upload the eGift card icon in refund option'
