fields:
  color:
    configurable: 1
    cardinality: 1
    index: 1
    facet: 1
  size:
    configurable: 1
    cardinality: 1
    index: 0
    facet: 0
  color_family:
    label: 'Color'
    type: 'string'
    cardinality: -1
    index: 0
    facet: 0
    swatch: 1
  size_shoe_eu:
    configurable: 1
    label: 'Size Shoes'
    cardinality: -1
    index: 1
    facet: 1
  size_shoe_uk:
    label: 'Size Shoes'
    cardinality: -1
    index: 1
    facet: 0
  size_shoe_us:
    label: 'Size Shoes'
    cardinality: -1
    index: 1
    facet: 0
  size_textile_eu:
    configurable: 1
    label: 'Size Clothing'
    cardinality: -1
    index: 1
    facet: 1
  size_textile_uk:
    label: 'Size Clothing'
    cardinality: -1
    index: 1
    facet: 0
  size_textile_us:
    label: 'Size Clothing'
    cardinality: -1
    index: 1
    facet: 0
  size_socks:
    configurable: 1
    label: 'Size Socks'
    cardinality: -1
    index: 1
    facet: 1
  size_bras:
    configurable: 1
    label: 'Size Bras'
    cardinality: -1
    index: 1
    facet: 1
  size_rest:
    configurable: 1
    label: 'Size Rest'
    cardinality: -1
    index: 1
    facet: 1
  product_brand:
    source: 'brand'
  material:
    label: 'Material'
    type: 'string'
    index: 1
