image_thumb_gallery: true
color_swatches: true
color_swatches_show_product_image: true
show_variants_thumbnail_plp_gallery: true
show_parent_images_in_child: true
media_roles_to_hide_in_gallery: 'thumbnail'
swatches:
  pdp:
    - color
  plp:
    - color_family
hide_not_required_option: true
plp_slider:
  item: 3
  margin: 3
