# Schema for the configuration files of the alshaya store finder settings.

alshaya_stores_finder.settings:
  type: config_object
  label: 'Store finder configuration'
  mapping:
    enable_disable_store_finder_search:
      # Keeping this to integer as we don't want to enable/disable only for one language.
      type: integer
      label: 'Enable or disable store finder search on site'
    load_more_item_limit:
      type: integer
      label: 'Load more item count'
    search_proximity_radius:
      type: integer
      label: 'Store finder proximity radius'
