cart.get_cart:
    path: /cart/get
    controller: App\Controller\CartController::getCart
    methods: GET

cart.get_cart_for_checkout:
    path: /cart/checkout
    controller: App\Controller\CartController::getCartForCheckout
    methods: GET

cart.restore_cart:
    path: /cart/restore
    controller: App\Controller\CartController::restoreCart
    methods: GET

cart.update_cart:
    path: /cart/update
    controller: App\Controller\CartController::updateCart
    methods: POST

cart.associate_cart:
    path: /cart/associate
    controller: App\Controller\CartController::associateCart
    methods: GET

cart.place_order:
    path: /cart/place-order
    controller: App\Controller\CartController::placeOrder
    methods: POST

cart.place_order_system:
    path: /cart/place-order-system
    controller: App\Controller\CartController::placeOrderSystem
    methods: POST

cart.get_cnc_stores:
    path: /cart/stores/{lat}/{lon}
    controller: App\Controller\CartController::getCncStores
    methods: GET

payment.checkoutcom_payment_success:
    path: /payment/checkout-com-success
    controller: App\Controller\CheckoutComPaymentController::handleCheckoutComSuccess
    methods: GET

payment.checkoutcom_payment_error:
    path: /payment/checkout-com-error
    controller: App\Controller\CheckoutComPaymentController::handleCheckoutComError
    methods: GET

payment.checkout_com_apple_pay_save:
    path: /payment/checkout-com-apple-pay/save
    controller: App\Controller\CheckoutComPaymentController::saveApplePayPayment
    methods: POST

payment.knet_payment_response:
    path: /payment/knet-response
    controller: App\Controller\KnetPaymentController::handleKnetResponse
    methods: POST

payment.knet_payment_error:
    path: /payment/knet-error/{state_key}
    controller: App\Controller\KnetPaymentController::handleKnetError
    methods: GET

payment.cybersource_payment_token:
    path: /payment/cybersource/get-token
    controller: App\Controller\CyberSourcePaymentController::getCybersourceToken
    methods: POST

payment.cybersource_payment_finalise:
    path: /payment/cybersource/finalise
    controller: App\Controller\CyberSourcePaymentController::finaliseCybersource
    methods: POST

payment.payment_success:
  path: /payment/success/{langcode}
  controller: App\Controller\PaymentController::handlePaymentSuccess
  methods: GET

payment.payment_error:
  path: /payment/error/{langcode}
  controller: App\Controller\PaymentController::handlePaymentFail
  methods: GET

freegift.select_free_gift:
    path: /select-free-gift
    controller: App\Controller\FreeGiftController::selectFreeGift
    methods: POST
