alshaya_acm_product.display_settings:
  type: config_object
  label: 'Alshaya ACM Product display settings'
  mapping:
    image_thumb_gallery:
      type: boolean
      label: 'Display image thumb gallery on product node'
    color_swatches:
      type: boolean
      label: 'Display color swatches on product node'
    plp_slider:
      type: mapping
      label: 'Configuration for plp slider'
      mapping:
        items:
          type: integer
          label: 'Number of items to display in slider'
        margin:
          type: integer
          label: 'Margin between images in slider'
    short_desc_characters:
      type: integer
      label: 'No. of characters that should be displayed as short decription on PDP page.'
    short_desc_text_summary:
      type: boolean
      label: 'Use text_summary to generate short description.'
    show_color_images_on_filter:
      type: integer
      label: 'Flag to show images from specific color on filter.'
    show_brand_name_plp:
      type: boolean
      label: 'Flag to show brand name on plp/srp teaser view.'
    show_variants_thumbnail_plp_gallery2:
      type: boolean
      label: 'Show swatches in carousel view.'
    size_group:
      type: mapping
      label: 'Configuration for size grouping.'
      mapping:
        pdp:
          type: string
          label: 'Attribute to identify for size grouping.'
        alternates:
          type: sequence
          label: 'Attribute codes and labels to be used for grouping.'
          sequence:
            type: mapping
            label: 'Group options value with label'
            mapping:
              value:
                type: string
                label: 'Value'
              label:
                type: label
                label: 'Label'
    change_matchback_color:
      type: boolean
      label: 'Change matchback color on main product color change'
    use_matchback_cart_notification:
      type: boolean
      label: 'On add to cart, show the matchback cart notification'
    display_mobile_matchback_add_to_bag_button:
      type: boolean
      label: 'Show add to bag button on mathcback mobile'
    show_pre_selected_variant_on_pdp:
      type: boolean
      label: 'Show a pre selected variant on PDP page load'
    pdp_title_attributes:
      type: string
      label: 'Attributes to be displayed on PDP title.'
