alshaya_spc.settings:
  type: config_object
  label: 'Alshaya spc configuration'
  mapping:
    order_id_fallback:
      type: string
      label: 'Order id fallback if new encrypted parameter not available'
    subtotal_after_discount:
      type: boolean
      label: 'To show/hide subtotal after discount on cart/checkout page.'
    cod_mobile_verification:
      type: boolean
      label: 'Turn on / off cash on delivery payment method mobile otp verification'
    display_cart_payment_icons:
      type: boolean
      label: 'Display payment method icons on cart page'
    show_notification_drawer:
      type: boolean
      label: 'Enable drawer panel to show cart notification'
    redirect_to_cart_threshold:
      type: mapping
      label: 'Redirect to cart threshold.'
      mapping:
        mobile:
          type: integer
          label: 'Mobile configuration'
        desktop:
          type: integer
          label: 'Desktop configuration'
    validate_order_on_payment_failure:
      type: boolean
      label: 'To determine if we need to validate order on payment failure.'

alshaya_spc.click_n_collect:
  type: config_object
  label: 'spc click and collect configuration'
  mapping:
    country_center:
      type: mapping
      label: 'Center of Country to fetch stores'
      mapping:
        latitude:
          type: float
          label: 'latitude'
        longitude:
          type: float
          label: 'longitude'
        zoom:
          type: integer
          label: 'map zoom for country.'
    cnc_stores_limit:
      type: integer
      label: 'CnC stores limit'

alshaya_spc.advantage_card:
  type: config_object
  label: 'Advantage Card configuration'
  mapping:
    advantageCardEnabled:
      type: boolean
      label: 'Advantage card status'
    advantageCardPrefix:
      type: string
      label: 'Advantage card prefix'

alshaya_spc.express_delivery:
  type: config_object
  label: 'Delivery options configuration'
  mapping:
    same_day_delivery_status:
      type: boolean
      label: 'Same Day delivery status'
    express_delivery_status:
      type: boolean
      label: 'Express delivery status'
    delivery_options_order:
      type: sequence
      label: 'Delivery options order'
      sequence:
        type: string
        label: 'Delivery option type'
    same_day_delivery_label:
      type: string
      label: 'Same Day Delivery Label'
    express_delivery_label:
      type: string
      label: 'Express Delivery Label'

alshaya_spc.show_listing_sidebar:
  type: config_object
  label: 'Show hide sidebar on PLP/SRP pages'
  mapping:
    show_plp_sidebar:
      type: boolean
      label: 'Enable PLP sidebar'
    show_srp_sidebar:
      type: boolean
      label: 'Enable SRP sidebar'
