alshaya_wishlist.settings: 
  type: config_object
  label: 'Alshaya Wishlist Configuration'
  mapping:
    wishlist_enabled:
      type: boolean
      label: 'Switch to enable and disable Wishlist.'
    empty_wishlist_message:
      type: text
      label: 'Empty Wishlist Message.'
